// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"yxb.com/gin-scaffold/v2/internal/app/api/v1"
	"yxb.com/gin-scaffold/v2/internal/app/dao/user"
	"yxb.com/gin-scaffold/v2/internal/app/router"
	"yxb.com/gin-scaffold/v2/internal/app/service"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, error) {
	db, err := InitGormDB()
	if err != nil {
		return nil, err
	}
	repo := &user.Repo{
		DB: db,
	}
	userSvc := &service.UserSvc{
		UserRepo: repo,
	}
	userApi := &v1.UserApi{
		UserSvc: userSvc,
	}
	routerRouter := &router.Router{
		UserApi: userApi,
	}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine: engine,
	}
	return injector, nil
}
