httpServer:
  host: 127.0.0.1
  port: 8080

casbin:
  enabled: 1
  model: "./config/casbin_model.conf"

logger:
  ## 日志级别 (1:fatal 2:error,3:warn,4:info,5:debug,6:trace)
  level: 1
  ## 日志格式（支持输出格式：text/json）
  format: text
  ## 日志输出 (支持：stdout/stderr/file)
  output: stdout

  # 指定日志输出的文件路径
  outPutFile: "logs/gin-admin.log"
  # 是否启用日志钩子
  enableHook: false
  # 写入钩子的日志级别
  hookLevels: ["info", "warn", "error"]
  # 日志钩子(支持：gorm/mongo)
  hook: "gorm"
  # 写入钩子的最大工作线程数量
  hookMaxThread: 1
  # 写入钩子的最大缓冲区数量
  hookMaxBuffer: 512
  # 日志轮询数量
  rotationCount: 20
  # 日志轮询时间周期
  rotationTime: 24


gorm:
  # 是否开启调试模式
  debug: true
  # 数据库类型(目前支持的数据库类型：mysql/sqlite3/postgres)
  dBType: "mysql"
  # 设置连接可以重用的最长时间(单位：秒)
  maxLifetime: 7200
  # 设置数据库的最大打开连接数
  maxOpenConns: 150
  # 设置空闲连接池中的最大连接数
  maxIdleConns: 50
  # 数据库表名前缀
  tablePrefix: "g_"
  # 是否启用自动映射数据库表结构
  enableAutoMigrate: true

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  pwd: 123456
  dbname: yxb
  parameters: charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true

sqlite3:
  path: "data/sqlite.db"

redis:
  host: 127.0.0.1
  port: 6379
  db: 10
  pwd: ""

jwt:
  enabled: 1
  signingMethod: HS512
  signingKey: "JYex2hx19HGG3"